package cl;

import android.os.Parcel;
import kotlin.NotImplementedError;
import yt.k;

/* JADX INFO: loaded from: classes5.dex */
public interface c<T> {

    public static final class a {
        @k
        public static <T> T[] a(@k c<T> cVar, int i10) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    void a(T t10, @k Parcel parcel, int i10);

    T b(@k Parcel parcel);

    @k
    T[] newArray(int i10);
}
