package dp;

import java.io.PrintStream;
import java.math.BigInteger;
import java.security.SecureRandom;
import org.bouncycastle.crypto.CryptoException;
import vo.c;
import vo.d;
import vo.e;
import vo.f;
import zo.e0;

/* JADX INFO: loaded from: classes5.dex */
public class b {
    public static BigInteger a(BigInteger bigInteger) {
        e0 e0Var = new e0();
        byte[] byteArray = bigInteger.toByteArray();
        byte[] bArr = new byte[e0Var.h()];
        e0Var.update(byteArray, 0, byteArray.length);
        e0Var.c(bArr, 0);
        return new BigInteger(bArr);
    }

    public static void b(String[] strArr) throws CryptoException {
        vo.b bVar = c.f53322c;
        BigInteger bigIntegerB = bVar.b();
        BigInteger bigIntegerC = bVar.c();
        BigInteger bigIntegerA = bVar.a();
        System.out.println("********* Initialization **********");
        System.out.println("Public parameters for the cyclic group:");
        System.out.println("p (" + bigIntegerB.bitLength() + " bits): " + bigIntegerB.toString(16));
        System.out.println("q (" + bigIntegerC.bitLength() + " bits): " + bigIntegerC.toString(16));
        System.out.println("g (" + bigIntegerB.bitLength() + " bits): " + bigIntegerA.toString(16));
        PrintStream printStream = System.out;
        StringBuilder sb2 = new StringBuilder();
        sb2.append("p mod q = ");
        sb2.append(bigIntegerB.mod(bigIntegerC).toString(16));
        printStream.println(sb2.toString());
        System.out.println("g^{q} mod p = " + bigIntegerA.modPow(bigIntegerC, bigIntegerB).toString(16));
        System.out.println("");
        System.out.println("(Secret passwords used by Alice and Bob: \"password\" and \"password\")\n");
        e0 e0Var = new e0();
        SecureRandom secureRandom = new SecureRandom();
        vo.a aVar = new vo.a("alice", "password".toCharArray(), bVar, e0Var, secureRandom);
        vo.a aVar2 = new vo.a("bob", "password".toCharArray(), bVar, e0Var, secureRandom);
        d dVarB = aVar.b();
        d dVarB2 = aVar2.b();
        System.out.println("************ Round 1 **************");
        System.out.println("Alice sends to Bob: ");
        System.out.println("g^{x1}=" + dVarB.a().toString(16));
        System.out.println("g^{x2}=" + dVarB.b().toString(16));
        System.out.println("KP{x1}={" + dVarB.c()[0].toString(16) + "};{" + dVarB.c()[1].toString(16) + zc.a.f58317e);
        System.out.println("KP{x2}={" + dVarB.d()[0].toString(16) + "};{" + dVarB.d()[1].toString(16) + zc.a.f58317e);
        System.out.println("");
        System.out.println("Bob sends to Alice: ");
        System.out.println("g^{x3}=" + dVarB2.a().toString(16));
        System.out.println("g^{x4}=" + dVarB2.b().toString(16));
        System.out.println("KP{x3}={" + dVarB2.c()[0].toString(16) + "};{" + dVarB2.c()[1].toString(16) + zc.a.f58317e);
        System.out.println("KP{x4}={" + dVarB2.d()[0].toString(16) + "};{" + dVarB2.d()[1].toString(16) + zc.a.f58317e);
        System.out.println("");
        aVar.f(dVarB2);
        System.out.println("Alice checks g^{x4}!=1: OK");
        System.out.println("Alice checks KP{x3}: OK");
        System.out.println("Alice checks KP{x4}: OK");
        System.out.println("");
        aVar2.f(dVarB);
        System.out.println("Bob checks g^{x2}!=1: OK");
        System.out.println("Bob checks KP{x1},: OK");
        System.out.println("Bob checks KP{x2},: OK");
        System.out.println("");
        e eVarC = aVar.c();
        e eVarC2 = aVar2.c();
        System.out.println("************ Round 2 **************");
        System.out.println("Alice sends to Bob: ");
        System.out.println("A=" + eVarC.a().toString(16));
        System.out.println("KP{x2*s}={" + eVarC.b()[0].toString(16) + "},{" + eVarC.b()[1].toString(16) + zc.a.f58317e);
        System.out.println("");
        System.out.println("Bob sends to Alice");
        System.out.println("B=" + eVarC2.a().toString(16));
        System.out.println("KP{x4*s}={" + eVarC2.b()[0].toString(16) + "},{" + eVarC2.b()[1].toString(16) + zc.a.f58317e);
        System.out.println("");
        aVar.g(eVarC2);
        System.out.println("Alice checks KP{x4*s}: OK\n");
        aVar2.g(eVarC);
        System.out.println("Bob checks KP{x2*s}: OK\n");
        BigInteger bigIntegerA2 = aVar.a();
        BigInteger bigIntegerA3 = aVar2.a();
        System.out.println("********* After round 2 ***********");
        System.out.println("Alice computes key material \t K=" + bigIntegerA2.toString(16));
        System.out.println("Bob computes key material \t K=" + bigIntegerA3.toString(16));
        System.out.println();
        a(bigIntegerA2);
        a(bigIntegerA3);
        f fVarD = aVar.d(bigIntegerA2);
        f fVarD2 = aVar2.d(bigIntegerA3);
        System.out.println("************ Round 3 **************");
        System.out.println("Alice sends to Bob: ");
        System.out.println("MacTag=" + fVarD.a().toString(16));
        System.out.println("");
        System.out.println("Bob sends to Alice: ");
        System.out.println("MacTag=" + fVarD2.a().toString(16));
        System.out.println("");
        aVar.h(fVarD2, bigIntegerA2);
        System.out.println("Alice checks MacTag: OK\n");
        aVar2.h(fVarD, bigIntegerA3);
        System.out.println("Bob checks MacTag: OK\n");
        System.out.println();
        System.out.println("MacTags validated, therefore the keying material matches.");
    }
}
